services:
  laos-sim-app:
    build: .
    image: laos-sim-app
    container_name: laos-sim-app
    restart: unless-stopped
    mem_limit: 128m
    ports:
      - "8421:80"
    networks:
      - swag-network
    labels:
      - "swag=enable"
      - "swag_address=laos-sim-app"
      - "swag_port=80"
      - "swag_url=laos-sim.shellnode.lol"
      - "homepage.instance=my-vps"
      - "homepage.name=Laos SIM"
      - "homepage.group=Laos"
      - "homepage.href=https://laos-sim.shellnode.lol"
      - "homepage.icon=mdi-sim"
      - "homepage.description=Laos SIM card comparison guide"

networks:
  swag-network:
    external: true
